let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
basic.forever(function () {
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    basic.pause(1000)
    strip.rotate(1)
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Purple))
    basic.pause(1000)
    strip.rotate(1)
})
